<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYAPKLsi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYAPKLsi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYAPKLsi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYAPKLsi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYAPKLsi\App_KernelDevDebugContainer([
    'container.build_hash' => 'YAPKLsi',
    'container.build_id' => '6bf3cdd6',
    'container.build_time' => 1680066576,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYAPKLsi');
