<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2NneQ7T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2NneQ7T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2NneQ7T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2NneQ7T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2NneQ7T\App_KernelDevDebugContainer([
    'container.build_hash' => '2NneQ7T',
    'container.build_id' => 'fc440117',
    'container.build_time' => 1680087862,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2NneQ7T');
