version: '3.7'
services:
  php:
    image: arijkortas/gestion_formations:php
    container_name: phpC
    ports: ['9000:9000']
    volumes: ['./app/:/var/www/app:cached']
  nginx:
    image: arijkortas/gestion_formations:nginx
    ports: ['80:80']
    volumes: ['./app/:/var/www/app:cached']
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db_formation
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example